[package]
name = "CreatureBattleSimulator"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
uuid = { version = "1.9.1", features = ["v4", "serde"] }
surrealdb = "1.5.3"